---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make black_check
        language: system
        stages:
          - commit
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: make isort_check
        language: system
        stages:
          - commit
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: make flake8
        language: system
        stages:
          - commit
  - repo: local
    hooks:
      - id: pytest_staged
        name: pytest staged
        entry: make test_staged
        language: system
        stages:
          - commit
  - repo: local
    hooks:
      - id: pytest
        name: pytest full
        entry: make test
        language: system
        stages:
          - push